version: 0.2
phases:
  install:
    commands:
      - go get
  pre_build:
    commands:
      - golint -set_exit_status
      - echo no go test
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo no postbuild commands
artifacts:
  files:
    - product-web